apiVersion: v1
kind: Pod
metadata:
  name: nyan-cat
  labels:
    app.kubernetes.io/name: nyan-cat
spec:
  containers:
    - name: nyan-cat
      image: rogerwesterbo/nyan-cat:0.0.8
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: temp
          mountPath: /tmp
  volumes:
    - name: temp
      persistentVolumeClaim:
        claimName: nyan-cat
