apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    namespace: opencost
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: opencost
    helm:
      parameters:
        - name: opencost.prometheus.internal.namespaceName
          value: prometheus
        - name: opencost.prometheus.internal.serviceName
          value: prometheus-kube-prometheus-prometheus
        - name: opencost.prometheus.internal.port
          value: '9090'
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: '*'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
